const mockDataPublikasi = [
    {
        id : 'a1',
        title : 'Buku Profil Kota Makassar Tahun 2022',
        bidang : 'Bidang Pengolahan Data Elektronik Diskominfo Makassar',
        date : '30 Februari 2024',
        image : '/images/Cover_publikasi1687309158 2.png',
        fileLink : 'https://www.google.com',
        views: 100,
    },
    {
        id : 'a2',
        title : 'Buku Profil Kota Makassar Tahun 2022',
        bidang : 'Bidang Pengolahan Data Elektronik Diskominfo Makassar',
        date : '30 Februari 2024',
        image : '/images/Cover_publikasi1687309158 2.png',
        fileLink : 'https://www.google.com',
        views: 100,
    },
    {
        id : 'a3',
        title : 'Buku Profil Kota Makassar Tahun 2022',
        bidang : 'Bidang Pengolahan Data Elektronik Diskominfo Makassar',
        date : '30 Februari 2024',
        image : '/images/Cover_publikasi1687309158 2.png',
        fileLink : 'https://www.google.com',
        views: 100,
    },
    {
        id : 'a4',
        title : 'Buku Profil Kota Makassar Tahun 2022',
        bidang : 'Bidang Pengolahan Data Elektronik Diskominfo Makassar',
        date : '30 Februari 2024',
        image : '/images/Cover_publikasi1687309158 2.png',
        fileLink : 'https://www.google.com',
        views: 100,
    },
    {
        id : 'a5',
        title : 'Buku Profil Kota Makassar Tahun 2022',
        bidang : 'Bidang Pengolahan Data Elektronik Diskominfo Makassar',
        date : '30 Februari 2024',
        image : '/images/Cover_publikasi1687309158 2.png',
        fileLink : 'https://www.google.com',
        views: 100,
    },
    {
        id : 'a6',
        title : 'Buku Profil Kota Makassar Tahun 2022',
        bidang : 'Bidang Pengolahan Data Elektronik Diskominfo Makassar',
        date : '30 Februari 2024',
        image : '/images/Cover_publikasi1687309158 2.png',
        fileLink : 'https://www.google.com',
        views: 100,
    },
    {
        id : 'a7',
        title : 'Buku Profil Kota Makassar Tahun 2022',
        bidang : 'Bidang Pengolahan Data Elektronik Diskominfo Makassar',
        date : '30 Februari 2024',
        image : '/images/Cover_publikasi1687309158 2.png',
        fileLink : 'https://www.google.com',
        views: 100,
    },
    {
        id : 'a8',
        title : 'Buku Profil Kota Makassar Tahun 2022',
        bidang : 'Bidang Pengolahan Data Elektronik Diskominfo Makassar',
        date : '30 Februari 2024',
        image : '/images/Cover_publikasi1687309158 2.png',
        fileLink : 'https://www.google.com',
        views: 100,
    },
    {
        id : 'a9',
        title : 'Buku Profil Kota Makassar Tahun 2022',
        bidang : 'Bidang Pengolahan Data Elektronik Diskominfo Makassar',
        date : '30 Februari 2024',
        image : '/images/Cover_publikasi1687309158 2.png',
        fileLink : 'https://www.google.com',
        views: 100,
    },
    {
        id : 'a10',
        title : 'Buku Profil Kota Makassar Tahun 2022',
        bidang : 'Bidang Pengolahan Data Elektronik Diskominfo Makassar',
        date : '30 Februari 2024',
        image : '/images/Cover_publikasi1687309158 2.png',
        fileLink : 'https://www.google.com',
        views: 100,
    },
    {
        id : 'a11',
        title : 'Buku Profil Kota Makassar Tahun 2022',
        bidang : 'Bidang Pengolahan Data Elektronik Diskominfo Makassar',
        date : '30 Februari 2024',
        image : '/images/Cover_publikasi1687309158 2.png',
        fileLink : 'https://www.google.com',
        views: 100,
    },
    {
        id : 'a12',
        title : 'Buku Profil Kota Makassar Tahun 2022',
        bidang : 'Bidang Pengolahan Data Elektronik Diskominfo Makassar',
        date : '30 Februari 2024',
        image : '/images/Cover_publikasi1687309158 2.png',
        fileLink : 'https://www.google.com',
        views: 100,
    }
]

export default mockDataPublikasi;