export type CollegeStudent = {
  namemahasiswa: string;
  nim: string;
  nilai: string;
  status: string;
  nilai_kehadiran: number,
  nilai_keaktifan: number,
  nilai_uts: number,
  nilai_tugas: number,
  nilai_uas: number,
};

export const dataCollege: CollegeStudent[] = [
  {
    namemahasiswa: "Ahmad Eko",
    nim: "D11111111",
    nilai: "a",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Budi Santoso",
    nim: "D11111112",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Citra Wijaya",
    nim: "D11111113",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Dewi Sari",
    nim: "D11111114",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {  
      namemahasiswa: "Eka Putra",
    nim: "D11111115",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Fauzi Rahman",
    nim: "D11111116",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Gita Wulandari",
    nim: "D11111117",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Hadi Sutomo",
    nim: "D11111118",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Ira Setiawan",
    nim: "D11111119",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Joko Susilo",
    nim: "D11111120",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Kartika Sari",
    nim: "D11111121",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Lia Ramadhani",
    nim: "D11111122",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Maulana Malik",
    nim: "D11111123",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Nadia Putri",
    nim: "D11111124",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Oscar Nugroho",
    nim: "D11111125",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Putri Ayu",
    nim: "D11111126",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Qori Hidayat",
    nim: "D11111127",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Rizky Pratama",
    nim: "D11111128",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Siti Aminah",
    nim: "D11111129",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Taufik Hidayat",
    nim: "D11111130",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Umi Kusuma",
    nim: "D11111131",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Vino Wijaya",
    nim: "D11111132",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Wahyu Setiawan",
    nim: "D11111133",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Xena Putri",
    nim: "D11111134",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Yogi Pratama",
    nim: "D11111135",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Zara Salsabila",
    nim: "D11111136",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Adi Kusuma",
    nim: "D11111137",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Bayu Pratama",
    nim: "D11111138",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Cindy Wijaya",
    nim: "D11111139",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Dian Pratiwi",
    nim: "D11111140",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Eko Wahyudi",
    nim: "D11111141",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Fira Aulia",
    nim: "D11111142",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Gilang Santosa",
    nim: "D11111143",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },

  {
    namemahasiswa: "Hendra Pratama",
    nim: "D11111144",
    nilai: "-",
    status: "-",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
  },
];

